# Generated by Django 5.2 on 2025-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('post_date', models.DateField()),
                ('image', models.ImageField(upload_to='static/images')),
                ('paragraph', models.TextField(max_length=600)),
            ],
        ),
    ]
